name: Test

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v5

      - name: Install swag
        run: go install github.com/swaggo/swag/cmd/swag@latest

      - name: Checkout PocketID repo
        uses: actions/checkout@v6
        with:
          repository: 'pocket-id/pocket-id'
          ref: 'v2.2.0'
          path: 'pocket-id'

      - name: Generate swagger.json
        working-directory: pocket-id/backend
        run: |
          mkdir -p ../../generated
          echo "Pocket ID API" > ../../generated/api.md
          swag init -d ./internal,./internal/dto -g ../cmd/main.go -ot json -o ../../generated -md ../../generated

      - name: Cleanup PocketID repo
        run: rm -rf pocket-id

      - name: Generate PocketID client
        run: |
          npm i --include=dev
          npx openapi \
            --input generated/swagger.json \
            --output ./dist/pocketid-client \
            --client fetch

      - name: Build Pepr module
        run: |
          npx pepr build
