name: Test

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v5

      - name: Install swag
        run: go install github.com/swaggo/swag/cmd/swag@latest

      - uses: actions/checkout@v6
        with:
          repository: 'pocket-id/pocket-id'
          ref: 'v2.2.0'
          path: 'pocket-id'

      - name: Generate swagger.json
        run: |
          cd pocket-id/backend
          swag init -d ./internal,./internal/dto -g ../cmd/main.go -ot json -o ../../static -md ../../static
        
      - name: Generate PocketID client
        run: |
          mkdir dist
          mv pocket-id/backend/swagger.json dist/swagger.json
          npm i -D openapi-typescript-codegen
          npx openapi \
            --input dist/swagger.json \
            --output ./dist/pocketid-client \
            --client fetch

      - name: Build Pepr module
        run: |
          npx pepr build
